#!/bin/sh
# Vercel build-time env.js generator (Story 4.1 C1 fix, 2026-05-27 code-review).
#
# 정적 dashboard(vanilla HTML+JS, no Next.js)가 `window.RANKBIDDER_*` 글로벌 변수로
# Bearer 토큰과 API base URL을 받음. Vercel은 환경변수를 자동 주입하지 않으므로
# 빌드 시점에 public/static/js/env.js 파일을 동적 생성해서 HTML이 `<script>`로 로드.
#
# **보안 경고**: env.js는 클라이언트에 그대로 노출됨. RANKBIDDER_AUTH_TOKEN이 페이지
# 소스에 보임 → 1인 운영용으로만 적합. SaaS화 시 Vercel Edge Function 프록시 전환 필요.
#
# Vercel Project Settings → Environment Variables:
# - RANKBIDDER_AUTH_TOKEN  (Production, Preview)
# - RANKBIDDER_API_BASE    (e.g., https://rank-bidder.duckdns.org)

set -eu

OUT="public/static/js/env.js"

AUTH_TOKEN="${RANKBIDDER_AUTH_TOKEN:-}"
API_BASE="${RANKBIDDER_API_BASE:-}"

# 빈 값 그대로 통과 — 로컬 dev에서는 localStorage fallback이 동작.
cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/build-env-js.sh at Vercel build time.
// DO NOT EDIT manually. Source = Vercel Project Environment Variables.
window.RANKBIDDER_AUTH_TOKEN = ${AUTH_TOKEN:+\"$AUTH_TOKEN\"};
window.RANKBIDDER_API_BASE = ${API_BASE:+\"$API_BASE\"};
EOF

echo "build-env-js: wrote $OUT (auth_token=${AUTH_TOKEN:+set}${AUTH_TOKEN:-empty}, api_base=${API_BASE:-empty})"
